version: 2.0
- command:
   name: tests
   execute:
      - gprbuild -P tests/driver/test_driver.gpr
      - tclsh others/tests.tcl $1
   description: Build and run Steam Sky unit tests X times (required argument how many times)
- command:
   name: debug
   execute:
      - gprbuild -P steamsky.gpr
   description: Build Steam Sky in debug mode
- command:
   name: release
   execute:
      - tclsh others/build.tcl
   description: Build Steam Sky in release mode
- command:
   name: analyze
   execute:
      - gprbuild -P steamsky.gpr -XMode=analyze
   description: Build Steam Sky in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P steamsky.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P steamsky.gpr
   description: Regenerate unit tests
- command:
   name: docs
   execute:
      - tclsh others/generatedocs.tcl
   description: Generate code documentation
- command:
   name: gprof
   execute:
      - gprof bin/steamsky gmon.out
   description: Generate gprof report
   flags:
      - unixonly
- command:
   name: windows
   execute:
      - sudo docker run --rm -w /app -v $1:/app ghcr.io/thindil/adabuildwin64 /bin/bash others/build.tcl x86_64-windows
   description: Build Steam Sky release for Windows on Linux, required argument is full path to the game source code
   flags:
      - unixonly
- command:
   name: pretty
   execute:
      - gnatpp -P steamsky.gpr
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print Steam Sky source code
- command:
   name: prettytests
   execute:
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print unit tests source code
- command:
   name: push
   execute:
      - fossil push
      - fossil git export --force
   description: Update remote Fossil repository and its Git mirror
   flags:
      - unixpath
- command:
   name: check
   execute:
      - sudo docker run --rm -w /app -v $1:/app ghcr.io/thindil/adabuild:9 /bin/bash others/check.tcl
   description: Run AdaControl to check correctness of the code required argument is full path to the program source code
   flags:
      - unixpath
- command:
   name: checkall
   execute:
      - bob debug
      - bob tests 20
      - bob check
   description: Run all the project tests
- command:
   name: checkfile
   execute:
      - sudo docker run --rm -w /app -v $1:/app ghcr.io/thindil/adabuild:9 /bin/bash others/check.tcl $2
   description: Run AdaControl to check correctness of the selected file. Required arguments are full path to the program source code and relative path to the file which will be check
   flags:
      - unixpath
