version: 2.0
- command:
   name: tests
   execute:
      - gprbuild -P tests/driver/test_driver.gpr
      - others/tests.sh $1
   description: Build and run Steam Sky unit tests X times (required argument how many times)
   flags:
      - unixonly
- command:
   name: debug
   execute:
      - gprbuild -P steamsky.gpr
   description: Build Steam Sky in debug mode
- command:
   name: release
   execute:
      - gprclean -P steamsky.gpr
      - others/build.tcl
      - gprclean -P steamsky.gpr
   description: Build Steam Sky in release mode
   flags:
      - unixonly
- command:
   name: analyze
   execute:
      - gprbuild -P steamsky.gpr -XMode=analyze
   description: Build Steam Sky in analyze mode
- command:
   name: clean
   execute:
      - gprclean -P steamsky.gpr
   description: Clean all compilation files
- command:
   name: createtests
   execute:
      - gnattest -P steamsky.gpr
   description: Regenerate unit tests
- command:
   name: docs
   execute:
      - others/generatedocs.tcl
   description: Generate code documentation
- command:
   name: gprof
   execute:
      - gprof bin/steamsky gmon.out
   description: Generate gprof report
   flags:
      - unixonly
- command:
   name: windows
   execute:
      - wineconsole others/build.cmd
   description: Build Steam sky release for Windows on Linux
   flags:
      - unixonly
- command:
   name: release
   execute:
      - others/build.cmd
   description: Build Steam sky in release mode
   flags:
      - windowsonly
- command:
   name: pretty
   execute:
      - gnatpp -P steamsky.gpr
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print Steam sky source code
- command:
   name: prettytests
   execute:
      - gnatpp -P tests/prettytests.gpr
   description: Pretty print unit tests source code
