#!/bin/sh

cd $APPDIR/usr/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPDIR/usr/lib
export GDK_PIXBUF_MODULE_FILE=$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
export GDK_PIXBUF_MODULEDIR=$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/
export FONTCONFIG_FILE=$APPDIR/usr/etc/fonts/fonts.conf
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$APPDIR/usr/share
export GSETTINGS_BACKEND=memory
export GTK_THEME=Adwaita
export RUNFROMSCRIPT=1
if [ $# -eq 0 ]
then
   ./steamsky --savedir="$HOME"/.local/share/steamsky/saves --themesdir="$HOME"/.local/share/steamsky/themes --modsdir="$HOME"/.local/share/steamsky/mods --datadir=$APPDIR/usr/share/data --docdir=$APPDIR/usr/share/doc
else
   ./steamsky "$@"
fi
