#!/bin/sh

cd $APPDIR/usr/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPDIR/usr/lib
export GDK_PIXBUF_MODULE_FILE=$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
export GDK_PIXBUF_MODULEDIR=$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/
export FONTCONFIG_FILE=$APPDIR/usr/etc/fonts/fonts.conf
export XDG_DATA_DIRS=$XDG_DATA_DIRS:$APPDIR/usr/share
export GSETTINGS_BACKEND=memory
export GTK_THEME=Adwaita
export RUNFROMSCRIPT=1
savedir="$HOME"/.local/share/steamsky/saves
themesdir="$HOME"/.local/share/steamsky/themes
modsdir="$HOME"/.local/share/steamsky/mods
datadir="$APPDIR"/usr/share/data
docdir="$APPDIR"/usr/share/doc
debug=none
while test $# -gt 0
do
   case "$1" in
      --savedir*) savedir=`echo $1 | sed -e 's/^[^=]*=//g'`
         ;;
      --themesdir*) themesdir=`echo $1 | sed -e 's/^[^=]*=//g'`
         ;;
      --modsdir*) modsdir=`echo $1 | sed -e 's/^[^=]*=//g'`
         ;;
      --datadir*) datadir=`echo $1 | sed -e 's/^[^=]*=//g'`
         ;;
      --docdir*) docdir=`echo $1 | sed -e 's/^[^=]*=//g'`
         ;;
      --debug*) debug=`echo $1 | sed -e 's/^[^=]*=//g'`
   esac
   shift
done
./steamsky --savedir="$savedir" --themesdir="$themesdir" --modsdir="$modsdir" --datadir="$datadir" --docdir="$docdir" --debug="$debug"
