name: Continuous Integration - development version

on:
  push:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: ghcr.io/thindil/build:10

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Debug build
      run: |
        git config --global --add safe.directory /__w/steamsky/steamsky
        nimble debug -y

    - name: Run the tests
      run: others/tests.nims 30

    - name: Check with Nimalyzer
      run: /root/.nimble/bin/nimalyzer others/nimalyzer.cfg

    - name: Upload the log
      uses: actions/upload-artifact@v6
      if: failure()
      with:
         name: nimalyzer.log
         path: nimalyzer.log

  cleanup:
    if: ${{ always() }}
    needs: tests

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Delete release
      run: gh release delete nightly -y
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build_linux:
    if: ${{ always() }}
    needs: cleanup

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/build:10

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build the program
      run: |
        git config --global --add safe.directory /__w/steamsky/steamsky
        others/build.nims linux

    - name: Compress the artifact
      run: |
        cd release
        tar -czf ../steamsky-development-linux.tar.gz steamsky-linux/

    - name: Upload to the nightly release
      uses: softprops/action-gh-release@v3
      with:
        files: steamsky-development-linux.tar.gz
        tag_name: nightly
        name: Nightly Development Release
        body: The daily development builds. Can be very unstable or buggy.
        prerelease: true

  build_windows:
    if: ${{ always() }}
    needs: build_linux

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/buildwin64:10

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build the program
      run: |
        git config --global --add safe.directory /__w/steamsky/steamsky
        others/build.nims windows

    - name: Compress the artifact
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r steamsky-development-windows.zip release/steamsky-windows/

    - name: Upload to the nightly release
      uses: softprops/action-gh-release@v3
      with:
        files: steamsky-development-windows.zip
        tag_name: nightly
        name: Nightly Development Release
        body: The daily development builds. Can be very unstable or buggy.
        prerelease: true

  build_freebsd:
    if: ${{ always() }}
    needs: build_windows

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build the program
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          pkg install -y git nimble ca_root_nss sdl2 sdl2_image
        run: |
          export PATH=$PATH:$HOME/.nimble/bin:/usr/local/nim/bin
          git config --global --add safe.directory /home/runner/work/steamsky/steamsky
          others/build.nims freebsd

    - name: Compress the artifact
      run: |
        cd release
        tar -czf ../steamsky-development-freebsd.tar.gz steamsky-freebsd/

    - name: Upload to the nightly release
      uses: softprops/action-gh-release@v3
      with:
        files: steamsky-development-freebsd.tar.gz
        tag_name: nightly
        name: Nightly Development Release
        body: The daily development builds. Can be very unstable or buggy.
        prerelease: true
